[project]
name = "handdrawn-signature-verifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dtaidistance>=2.3.13",
    "dtw-python>=1.5.3",
    "h5py>=3.13.0",
    "numba>=0.61.2",
    "numpy>=2.2.5",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "tslearn>=0.6.3",
]
